"""empty message

Revision ID: 8156a3e7fd37
Revises: 1b11ed301be3
Create Date: 2020-03-14 15:09:03.472644

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8156a3e7fd37'
down_revision = '1b11ed301be3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('language', sa.String(length=64), nullable=True))
    op.drop_column('movies', 'lanuage')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('lanuage', mysql.VARCHAR(length=64), nullable=True))
    op.drop_column('movies', 'language')
    # ### end Alembic commands ###
