"""empty message

Revision ID: c76b9b0b54c4
Revises: 840281d2ba9a
Create Date: 2020-04-04 16:04:09.533909

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c76b9b0b54c4'
down_revision = '840281d2ba9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('common_city',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('letter_id', sa.Integer(), nullable=True),
    sa.Column('c_id', sa.Integer(), nullable=True),
    sa.Column('c_parent_id', sa.Integer(), nullable=True),
    sa.Column('c_region_name', sa.String(length=16), nullable=True),
    sa.Column('c_city_code', sa.Integer(), nullable=True),
    sa.Column('c_pinyin', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['letter_id'], ['common_letter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('city')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('letter_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('c_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('c_parent_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('c_region_name', mysql.VARCHAR(length=16), nullable=True),
    sa.Column('c_city_code', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('c_pinyin', mysql.VARCHAR(length=64), nullable=True),
    sa.ForeignKeyConstraint(['letter_id'], ['common_letter.id'], name='city_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('common_city')
    # ### end Alembic commands ###
